//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxDoc.Test
{
    
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 博客表
    /// </summary>
    public partial class Blogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogs()
        {
            this.Posts = new HashSet<Posts>();
        }
    
    			
    	/// <summary>
        /// 博客主键
        /// </summary>
        public int BlogId { get; set; }
    			
    	/// <summary>
        /// 博客url
        /// </summary>
        public string Url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posts> Posts { get; set; }
    }
}
