
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxDoc.Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class TestContext : DbContext
    {
        
        public TestContext()
            : base("name=TestContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        
    	/// <summary>
        /// 博客表
        /// </summary>
        public virtual DbSet<Blogs> Blogs { get; set; }
    
    	/// <summary>
        /// 发帖表
        /// </summary>
        public virtual DbSet<Posts> Posts { get; set; }
    
    }
}
