//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxDoc.Test
{
    
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 发帖表
    /// </summary>
    public partial class Posts
    {
    			
    	/// <summary>
        /// 帖子主键(自增)
        /// </summary>
        public int PostId { get; set; }
    			
    	/// <summary>
        /// 博客ID
        /// </summary>
        public int BlogId { get; set; }
    			
    	/// <summary>
        /// 发帖内容
        /// </summary>
        public string Content { get; set; }
    			
    	/// <summary>
        /// 帖子标题
        /// </summary>
        public string Title { get; set; }
    
        public virtual Blogs Blogs { get; set; }
    }
}
